=== TheTridentGuy/dm32uv-codeplug-compiler/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "group_contacts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "number"
                    }
                },
                "required": [
                    "name",
                    "id"
                ]
            }
        },
        "private_contacts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "number"
                    }
                },
                "required": [
                    "name",
                    "id"
                ]
            }
        },
        "dmr_ids": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "number"
                    }
                },
                "required": [
                    "name",
                    "id"
                ]
            }
        },
        "default_dmr_id": {
            "type": "string"
        },
        "zones": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "channels": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string"
                                },
                                "uplink": {
                                    "type": "number"
                                },
                                "downlink": {
                                    "type": "number"
                                },
                                "ts1_contacts": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "ts2_contacts": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "required": [
                                "type",
                                "uplink",
                                "downlink"
                            ],
                            "anyOf": [
                                {
                                    "required": ["ts1_contacts"]
                                },
                                {
                                    "required": ["ts2_contacts"]
                                }
                            ]
                        }
                    }
                },
                "required": [
                    "name",
                    "channels"
                ]
            }
        }
    },
    "required": [
        "group_contacts",
        "private_contacts",
        "dmr_ids",
        "default_dmr_id",
        "zones"
    ]
}

=== TheTridentGuy/dm32uv-codeplug-compiler/codeplug.json
{
  "group_contacts": [
    {
      "name": "Lowell",
      "id": 5
    }
  ],
  "private_contacts": [],
  "dmr_ids": [
    {
      "name": "KO6ENZ",
      "id": 5
    },
    {
      "name": "Lowell",
      "id": 5
    }
  ],
  "default_dmr_id": "KO6ENZ",
  "zones": [
    {
      "name": "Mount Sutro",
      "channels": [
        {
          "name": "W6PW",
          "type": "digital",
          "uplink": 555.555,
          "downlink": 555.555,
          "uplink_cs": 1.0,
          "ts2_contacts": [
            "Worldwide",
            "NorCal"
          ]
        }
      ]
    },
    {
      "name": "Lowell",
      "channels": [
        {
          "name": "LWL",
          "type": "digital",
          "uplink": 555.555,
          "downlink": 555.555,
          "dmr_id": "Lowell",
          "ts1_contacts": [
            "Lowell"
          ]
        }
      ]
    }
  ]
}
